### ISSUE TITLE
Different extra options on a per-command basis

### ISSUE THREAD

**Issue by noplanman** [fiaasco/borgbackup#31]
As it is now, all options get applied to all commands in the `borg-backup.sh` and `prune.sh` scripts.
This only makes sense for global options, not command-specific ones.

I'd suggest to allow `options` parameter to be a dictionary, that allows extra options for each command. For backwards compatibility, a simple string mean global, as it is now.

(some pseudo-code)

e.g. now (options get set for every command)
```yaml
- borgbackup_servers:
   - fqdn: ch-s012.rsync.net
     user: 19574
     type: rsync.net
     home: ""
     pool: borgbackup
     options: "--remote-path=borg1"
```

e.g. after ("global" options get set for each command, and each sub-entry only for the specific command
```yaml
- borgbackup_servers:
  - fqdn: ch-s012.rsync.net
     user: 19574
     type: rsync.net
     home: ""
     pool: borgbackup
     options:
       global: "--remote-path=borg1"
       prune: "--kep-last 10"
       check: "--verify"
```
